name: 'Test development push'

on:
  pull_request:
    types: [submitted]
    branches:
      - 'feature/**'
      - 'develop'

permissions:
  contents: read

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Test with maven
        run: mvn clean test
